apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go
        image: containerappsstoragevolumeexamples-ephemeral-storage-go:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /usr/src/app/files
          name: ephemeralmount
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: ephemeralmount
        emptyDir:
          sizeLimit: 1G