apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python
        image: containerappsstoragevolumeexamples-ephemeral-storage-python:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /usr/src/app/files
          name: ephemeralmount
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name: ephemeralmount
          emptyDir:
            sizeLimit: 1G
          