apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php
        image: containerappsstoragevolumeexamples-ephemeral-storage-php:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/www/html/files
          name: ephemeralmount
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: ephemeralmount
        emptyDir:
          sizeLimit: 1G
          